MyBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.create_post, name='create_post'),
    path('like/<int:post_id>/', views.like_post, name='like_post'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    text = models.TextField(verbose_name='Текст')
    likes = models.IntegerField(default=0, verbose_name='Нравится')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Посты'
        verbose_name_plural = 'Пост'
        ordering = ['-title', 'author']

blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text']

blog/views.py
from django.shortcuts import render, redirect
from .forms import PostForm
from .models import Post
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required


def post_list(request):
    posts = Post.objects.all()
    return render(request, 'blog/post_list.html', {'posts': posts})


def post_detail(request, post_id):
    post = Post.objects.get(pk=post_id)
    return render(request, 'blog/post_detail.html', {'post': post})


@login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:post_list')
    else:
        form = PostForm()
    return render(request, 'blog/create_post.html', {'form': form})


def like_post(request, post_id):
    post = Post.objects.get(pk=post_id)
    post.likes += 1
    post.save()
    return JsonResponse({'likes': post.likes})

templates/blog/create_post.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Добавления поста</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col">
                <h1 class="mt-4">Новый пост</h1>
            </div>
        </div>
        <hr>

        <form method="post" action="{% url 'blog:create_post' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="title">Заголовок:</label>
                <input type="text" class="form-control" name="title" required>
            </div>
            <div class="form-group">
                <label for="text">Текст:</label>
                <textarea class="form-control" name="text" required></textarea>
            </div>
            <div class="row">
                <div class="col">
                    <button type="submit" class="btn btn-primary">Сохранить пост</button>
                </div>
                <div class="col">
                    <a href="{% url 'blog:post_list' %}" class="btn btn-danger float-right">Назад</a>
                </div>
            </div>
        </form>
    </div>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>

templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Информация</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .heart-red {
            fill: red;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="card mt-5">
            <div class="card-body">
                <h2 class="card-title">{{ post.title }}</h2>
                <p class="card-text">{{ post.text }}</p>
                <p class="card-text">
                    <span id="likes">{{ post.likes }}</span>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill heart-red" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"></path>
                    </svg>
                </p>
                <button class="btn btn-primary" onclick="likePost({{ post.id }})">
                    Мне нравится
                </button>
                <a href="{% url 'blog:post_list' %}" class="btn btn-danger float-right">Назад</a>
            </div>
        </div>
    </div>

    <script>
        function likePost(postId) {
            fetch('/like/' + postId + '/')
                .then(response => response.json())
                .then(data => {
                    const likesCount = document.getElementById('likes');
                    likesCount.innerText = data.likes;
                });
        }
    </script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>

templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Лист постов</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .center-text {
            text-align: center;
        }

        .create-post-btn {
            text-align: right;
        }

        .heart-red {
            color: red;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col">
                <h1 class="mt-4 mb-3 center-text">Список постов</h1>
            </div>
            <div class="col create-post-btn mt-5">
                <a href="{% url 'blog:create_post' %}" class="btn btn-primary">Новый пост</a>
            </div>
        </div>
        <hr>

        {% for post in posts %}
        <div class="card mb-4">
            <div class="card-body">
                <h2 class="card-title"><a href="{% url 'blog:post_detail' post_id=post.id %}">{{ post.title }}</a></h2>
                <p class="card-text">{{ post.text }}</p>
                <p class="card-text">Нравится: <span class="heart-red"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"></path>
                    </svg></span> {{ post.likes }}</p>
            </div>
        </div>
        {% endfor %}
    </div>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>